apiVersion: v1
kind: Secret
metadata: 
  name: db-credentials
  namespace: django-app-dev
type:  Opaque
stringData:
  DB_NAME: "finalexamdb"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "django-app-postgres.c4foywgea2nh.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT:  "6379"